A bit of report writing
albn-itu/algo2-red-scare pull request #27
Opened 2023-11-08 09:59 UTC by amalieboegild

2023-11-09 10:10 UTC, albe2669 requested changes

2023-11-09 10:10 UTC, albe2669 commented on report/report.tex
> +to find th shortest path which is what we are trying to achieve here.
th -> the

2023-11-09 10:10 UTC, albe2669 commented on report/report.tex
> +The runtime of BFS is O(V*E) where V are the number of vertices and E is the number of Edges.
Edges -> edges

2023-11-22 07:43 UTC, Arneproductions approved these changes

2023-11-22 07:44 UTC, albe2669 approved these changes

2023-11-22 07:44 UTC, merged